apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norppalive

resources:
  - ../../base
  - sealed-secret.yaml
  - service-account.yaml

images:
  - name: norppalive-discord
    newName: ghcr.io/dilaz/norppalive-discord
    newTag: sha-c30c87a712c479fd49a7389826ec15d85f2247e2

patches:
  - path: deployment-patch.yaml
