---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-bot-secrets
  namespace: norppalive
spec:
  encryptedData:
    DISCORD_TOKEN: AgA0fxVH776HhyxzLaQG5egnunUwIzZ05jRFtOicH38SibL3XMZJCfYcAbROTAFMBaOv7R6+lVpdvtZ0Q3705wppKELHdfm77cDfmIlhKDpNQY0INYOkS1WWI/nDfmNEezJiveGDLe37OgK8cQ9uyNWw81hJ6Vo1Tg6nEy6F+wpINDP+pomB/sftPo5aTdEpw0jCVelrHhO3zSPhCRfppXnmjsR35B1GLuroVDvakwNR5gmcpCHxB5vZvAGaCHcth5NdYYG6vtoeMuQ2bzCNHhGU0/xBiykWgDXYpABlwt/dACtPyeNcMm5m3qYWeqwOAxtVltwieqosRt4PW7OE5yxrvknLVtzTGoJVaBfXcXZgLH/6erlXw0Xf1rd1y/HKB9Eh9x3K0bck8t9hIfRsq6mvRXwGLPhRfdchWag2qBxklwwzMkT999jNpy20jfPLujaFpCn3c04G9DNMGduIMlpiJ6o55PUllBcmyIznGDXNe11OM08XLe5DIwspSPvNgCWCg7dBIkUnLy98nuwIjK3EwhORc9EuWI0pyX9ZNI0IRsY7n/tjwUHAQCkw6Yt7pB7bQGzE6FDTm0sL1DGMq86AhAW4tJfjrWHL01ZTUWCINgJl/sgt5Y1YWxJFD6LVTntiGNgZwadSe7JSNrszO0NZNRXsjbtbIHp8GqF8iVY/4C2Y/vf77IJ0f6wFk7JKEdh9P3FIIy+XMxayeCpPDOg4iGIDxK52XZJu8PhzG7017raMGyvv09VTtndbV8uWPlodj36k4vLuPr4vQ/w1fMBu6KFedCYJeoY=
  template:
    metadata:
      name: discord-bot-secrets
      namespace: norppalive
